version: '3.8'
services:
  create_order_service:
    build:
      context: .
      dockerfile: ./create_order/Dockerfile
    command: 'python create_order/create_order_service.py'
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    depends_on: 
      - db
  
  calculate_service:
    build:
      context: .
      dockerfile: ./calculate_order/Dockerfile
    command: 'python calculate_order/calculate_order_service.py'
    ports:
      - 5001:8000
    volumes: 
      - .:/calculate_order
    depends_on: 
      - db

  queue:
    build:
      context: .
      dockerfile: ./calculate_order/Dockerfile
    command: 'python -u calculate_order/consumer.py'
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
