version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

      
services:
  db:
    container_name: database
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - micro_network
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
