version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

      
services:
  process_orders_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:8000
    volumes: 
      - .:/order_processor_service
    networks:
      - micro_network

  queue:
    build:
      context: .
      dockerfile: consumer_dockerfile
    command: 'python -u consumer.py'
